# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(645, 395)
        MainWindow.setStyleSheet("* {\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"padding: 5px;\n"
"}")
        self.stylesheet = QtWidgets.QWidget(MainWindow)
        self.stylesheet.setStyleSheet("")
        self.stylesheet.setObjectName("stylesheet")
        self.gridLayout = QtWidgets.QGridLayout(self.stylesheet)
        self.gridLayout.setContentsMargins(-1, -1, 30, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.startTypingButton = QtWidgets.QPushButton(self.stylesheet)
        self.startTypingButton.setObjectName("startTypingButton")
        self.gridLayout.addWidget(self.startTypingButton, 3, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.documentFileLabel = QtWidgets.QLabel(self.stylesheet)
        self.documentFileLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.documentFileLabel.setObjectName("documentFileLabel")
        self.gridLayout.addWidget(self.documentFileLabel, 0, 0, 1, 1)
        self.documentFileInput = QtWidgets.QLineEdit(self.stylesheet)
        self.documentFileInput.setObjectName("documentFileInput")
        self.gridLayout.addWidget(self.documentFileInput, 0, 1, 1, 1)
        self.waitLabel = QtWidgets.QLabel(self.stylesheet)
        self.waitLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.waitLabel.setObjectName("waitLabel")
        self.gridLayout.addWidget(self.waitLabel, 2, 0, 1, 1)
        self.waitSpinBox = QtWidgets.QSpinBox(self.stylesheet)
        self.waitSpinBox.setObjectName("waitSpinBox")
        self.gridLayout.addWidget(self.waitSpinBox, 2, 1, 1, 1)
        self.chooseDocumentFileButton = QtWidgets.QPushButton(self.stylesheet)
        self.chooseDocumentFileButton.setMinimumSize(QtCore.QSize(0, 0))
        self.chooseDocumentFileButton.setAutoFillBackground(False)
        self.chooseDocumentFileButton.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-options-horizontal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chooseDocumentFileButton.setIcon(icon)
        self.chooseDocumentFileButton.setObjectName("chooseDocumentFileButton")
        self.gridLayout.addWidget(self.chooseDocumentFileButton, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 2)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 3)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 1)
        MainWindow.setCentralWidget(self.stylesheet)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Automate Typing"))
        self.startTypingButton.setText(_translate("MainWindow", "Start Typing"))
        self.documentFileLabel.setText(_translate("MainWindow", "Document (docx)"))
        self.waitLabel.setText(_translate("MainWindow", "Wait (in seconds)"))
        self.chooseDocumentFileButton.setStatusTip(_translate("MainWindow", "Either press Ctrl+O or click on it to choose Document File"))
        self.chooseDocumentFileButton.setText(_translate("MainWindow", "Choose File"))
